In [34]:
#将smile格式导出为xyz文件
from IPython.display import SVG
from rdkit import rdBase
from rdkit import Chem
from rdkit.Chem import AllChem, DataStructs
from rdkit.Chem.Draw import DrawMorganBit, DrawMorganBits,DrawMorganEnv, IPythonConsole
from rdkit.Chem import Draw
import pandas as pd
import matplotlib.pyplot as plt
import os
import numpy as np
from matplotlib import rcParams
config = {"mathtext.fontset":'stix'}
rcParams.update(config)

df=pd.read_excel('./reorganization/train_set_5631.xlsx',sheet_name="train_set_5631")

smiles = df.iloc[0:, [1]].values

for i in range(len(smiles)):
    mol = Chem.MolFromSmiles(smiles[i][0])
    mol_H = Chem.AddHs(mol)
    AllChem.EmbedMolecule(mol_H, randomSeed=10)
    AllChem.MMFFOptimizeMolecule(mol_H,mmffVariant='MMFF94', maxIters=200)
    Chem.MolToXYZFile(mol_H, str("%04d" % i)+'.xyz')
    


In [1]:
import numpy as np
a = np.array([[9,8,7],[3,4,6],[6,5,3]])
indexs = a.argsort()[:,::-1]    #将矩阵的每一行都降序排列，但不改变矩阵，且返回对应的索引
print(a)
print(indexs)


[[9 8 7]
 [3 4 6]
 [6 5 3]]
[[0 1 2]
 [2 1 0]
 [0 1 2]]


In [1]:
#将HOMO轨道的原子系数取出来
import shutil,re,os
import numpy as np
os.chdir('C:/Users/wanli/Desktop/ML/reorganization/data/orb-data') 
outFiles = []
for filename in os.listdir('./'): 
    if filename.endswith('.data'):
        outFiles.append(filename)       
outFiles.sort()

for i in outFiles:
    f_1 = open(i,'r')
    line = f_1.readlines()
    begin=[]
    end=[]
    for index,lines in enumerate(line):
        if "Contributions after normalization:" in lines:
            begin.append(index + 1)
        if "Orbital delocalization index:" in lines:
            end.append(index - 1)
            
#begin[0]对应HOMO,begin[1]对应LUMO
    coeff = np.loadtxt(i,skiprows=begin[0],max_rows=int(end[0]-begin[0]),usecols=(4),dtype=np.float)
    
    np.savetxt(str(i)[0:-5]+'-coeff.out',coeff/100,fmt='% 7.5f')
    


%reset

D:\study-setup\anaconda3\lib\site-packages\ipykernel_launcher.py:23: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


Once deleted, variables cannot be recovered. Proceed (y/[n])? y
